pirma užduotis
jugogugo/basicR pull request #16
Opened 2018-02-14 17:24 UTC by brigitaizganaityte

2018-02-14 17:36 UTC, jugogugo requested changes

2018-02-14 17:36 UTC, jugogugo commented on Brigita.rmd
> +```{r}
Trūksta antraštės

2018-02-14 18:10 UTC, brigitaizganaityte commented
Jei teisingai supratau, įkėliau pataisytą :)

2018-02-14 19:38 UTC, jugogugo commented
Ne, neteisingai, pasižiūrėk, kaip kiti padarė.

2018-02-14 20:14 UTC, jugogugo commented
Brigita, pabandykite savo kompiuteryje sugeneruoti visą puslapį, pasižiūrėkite, kas gaunasi. Ar tikrai viskas gerai?

2018-02-14 21:31 UTC, brigitaizganaityte commented
Jei šis padarytas netinkamai, tada tikrai nesuprantu į ką atkreipti dėmesį.

2018-02-14 21:45 UTC, jugogugo requested changes
- Nereikia įtraukti screen shot png į versionuojamą kodą, nes jis nėra kodo dalis

+ Tavo Rmd failas veikia, bet nepabandei pasižiūrėti į bendrą vaizdą. Sugeneruok visą puslapį savo kompiuteryje ir pasižiūrėk kaip tavo analizė integruojasi su kitomis.

2018-02-14 21:45 UTC, jugogugo commented on Brigita.Rmd
> +#BDA
Turėtų būti # Brigita ar kazkas panašaus

2018-02-14 21:45 UTC, jugogugo commented on Brigita.rmd
> +---
Kam reikalingi du atskiri failai tokiu pačiu pavadinimu, vienas .rmd, kitas .Rmd?

2018-02-14 21:45 UTC, jugogugo commented on _site.yml
> +    - text: "Brigita"
Čia kažkas ne taip. Turėtų pakeitimas būti susijęs tik su dviem Brigitos eilutėm, o ne su kitų studentų eilutėm.

2018-02-14 22:10 UTC, brigitaizganaityte commented
![screen](https://user-images.githubusercontent.com/36342343/36230884-a1ccb588-11e4-11e8-8f71-6914d7609847.png)

2018-02-14 22:41 UTC, brigitaizganaityte commented
Per klaidą parsisiunčiau Jūsų repozitoriją, o kadangi Jūs approvinot naujus žmonės, tikriausiai dėl to viskas siejasi jau ne tik su mano "Brigita" ir Brigita.html eilutėmis. Atsiprašau už sukeltus nepatogumus.

2018-02-15 09:15 UTC, jugogugo approved these changes

2018-02-15 09:15 UTC, merged